### ISSUE TITLE
[UMBRELLA APPS] Multiple phoenix apps support

### ISSUE THREAD

**Issue by bdubaut** [spandex-project/spandex_phoenix#20]
## Description

When running an Umbrella application, it is impossible to instrument 2 phoenix apps with `:spandex_phoenix`, because the configuration for the library only allows for one tracer module.  In other words, if one configures `:spandex_phoenix` like so:
```elixir
config :spandex_phoenix, tracer: MyApp1.Tracer
```
Then there is an exception raised because `MyApp2` does not have access to `MyApp1.Tracer`.

### Resources
Extracts from a conversation on Slack with @GregMefford & @zachdaniel:
![Screen Shot 2019-10-09 at 17 43 50](https://user-images.githubusercontent.com/798319/66497173-602fb000-eabc-11e9-9b5f-608b893076da.png)

Snippet from @zachdaniel (as a reminder):
```elixir
defmodule MyApp.Instrumenter do
  use SpandexPhoenix.Instrumenter, tracer: blah
end
```

_Hope this helps!_

**Comment by novaugust** [comment]
this should be doable w/ #31 by specifying the tracer during runtime in the telemetry installation options, rather than in application configuration. it still doesn't support multiple routers in one application since all routers send the same events, but i believe that'll cover the umbrella problem

**Comment by zachdaniel** [comment]
@novaugust They can use separate tracers w/ the same configuration for that, theoretically. Either way I think this is close enough to support for umbrella apps (given that they are using phx 1.5) that we can close this. Thanks!
