### ISSUE TITLE
Support Phoenix Telemetry events

### ISSUE THREAD

**Issue by GregMefford** [spandex-project/spandex_phoenix#23]
Phoenix will soon deprecate the `instrumenters` API that we currently use to collect instrumentation, in favor of `Telemetry` events: https://hexdocs.pm/phoenix/Phoenix.Endpoint.html#module-instrumentation

We should probably add some simple adapter functions to `SpandexPhoenix.Instrumenter` so that it will be an easy conversion to delegate to that module for either `instrumenters` or `Telemetry` events.

**Comment by egze** [comment]
Hi. Phoenix 1.5 is here.

Now it produces this warning:
`12:22:30.755 [warn] :instrumenters configuration for Web.Endpoint is deprecated and has no effect`

Is there any quick fix for this?

**Comment by novaugust** [comment]
@GregMefford I have a day or two of OSS time built up, I'll see if I can spike something up for this
