### ISSUE TITLE
Incompatible w/ spandex 3?

### ISSUE THREAD

**Issue by novaugust** [spandex-project/spandex_phoenix#27]
Pretty sure this just entails a bump in mix.exs since the breaking change was in adapters?
```
Failed to use "spandex" (version 3.0.1) because
  spandex_datadog (version 1.0.0) requires ~> 3.0
  spandex_phoenix (version 0.4.1) requires ~> 2.2
```

**Comment by zachdaniel** [comment]
Ah, yeah. need to do the same for spandex ecto. I’ll address it tomorrow, not at my computer today.

**Comment by zachdaniel** [comment]
Alright, this is done, and a minor version release has been created for this project and spandex ecto to account for the change.

**Comment by novaugust** [comment]
thanks @zachdaniel !
