### ISSUE TITLE
Feature Request/Question: Support sending filtered params with traces

### ISSUE THREAD

**Issue by aselder** [spandex-project/spandex_phoenix#34]
Often if a performance problem is identified, know the parameters that were passed in is critical in identifying the cause.

Right now, I don't see any parameter data being passed thru to datadog. Is there a way to do that (appropriately filtered of course)?

**Comment by novaugust** [comment]
Depending on which params you're talking about, it should be going out via the default_metadata function
https://github.com/spandex-project/spandex_phoenix/blob/eb491ee60d91babf71780141d603b7e618965992/lib/spandex_phoenix.ex#L183-L206
if you want other params in there, you can specify your own `:customize_metadata` option.
But of course it could also be that the phx 1.5 telemetry integration still isn't all the way there, so lemme know if something's not appearing that should be

**Comment by aselder** [comment]
What key would I put that in the custom metadata? Would it be under the http key?

**Comment by zachdaniel** [comment]
Just use custom keys (not the `http` key). We're actually ignoring that `query_string` metadata (which is a good thing, we'd be dumping all parameters that way) in `spandex_datadog` https://github.com/spandex-project/spandex_datadog/blob/master/lib/spandex_datadog/api_server.ex#L297

**Comment by zachdaniel** [comment]
So your function could look something like:

```
defmodule MyMod do
  def custom_metadata(conn) do
    conn
    |> SpandexPhoenix.default_metadata()
    |> add_query_parameters(conn)
  end

  defp add_query_parameters(metadata, conn) do
    parameters = Map.take(conn.query_params, ["my", "allowed", "parameters"])
    # or
    parameters = Map.drop(conn.query_params, ["my", "not", "allowed"])

    Keyword.put(metadata, :query, URI.encode_query(parameters))
  end
end
```

Its possible that datadog does something fancy w/ query parameters if you have it at `[http: [query_string: ...]]` but I don't think so. You might want to try it with both.

**Comment by aselder** [comment]
Thanks @zachdaniel. Looking at the datadog client, I'm not sure that would get sent to DD? Would I have to add it under the `tags` key, because it looks like arbitrary keys aren't sent.

**Comment by zachdaniel** [comment]
@aselder *great* catch :) It wasn't originally like that, and I forgot that we had made that change (ages ago, but I still forgot).

**Comment by zachdaniel** [comment]
I'm going to close this, as there is a relatively easy way to add query parameters to metadata. If anyone wants to contribute a utility/configuration to do this automatically I'd accept that change.
