### ISSUE TITLE
use SpandexPhoenix performs differently than :ok = SpandexPhoenix.Telemetry.install()

### ISSUE THREAD

**Issue by SophisticaSean** [spandex-project/spandex_phoenix#38]
If you `use SpandexPhoenix` in your phoenix endpoint definition you'll get logging that starts with a trace/span like this: 

```
15:24:52.849 request_id=Fi1li45gFHjqp4cAAAMD trace_id=722764706085105469 span_id=4753091734181075568 [info] POST /api/add_user
...
15:24:52.895 request_id=Fi1li45gFHjqp4cAAAMD trace_id=722764706085105469 span_id=9102789260387844769 [warn] Bad request in Example.UserController, error: :cannot_overwrite_user
15:24:52.895 request_id=Fi1li45gFHjqp4cAAAMD trace_id=722764706085105469 span_id=9102789260387844769 [info] Sent 400 in 45ms
```

If you just attach to telemetry via `:ok = SpandexPhoenix.Telemetry.install()`

It results in this:
```
15:24:52.849 request_id=Fi1li45gFHjqp4cAAAMD  [info] POST /api/add_user
...
15:24:52.895 request_id=Fi1li45gFHjqp4cAAAMD trace_id=722764706085105469 span_id=9102789260387844769 [warn] Bad request in Example.UserController, error: :cannot_overwrite_user
15:24:52.895 request_id=Fi1li45gFHjqp4cAAAMD trace_id=722764706085105469 span_id=9102789260387844769 [info] Sent 400 in 45ms
```

As you can see, the initial log from the POST is missing the trace_id and span_id.

**Comment by novaugust** [comment]
> make it seem like this is a required upgrade step

Yeah, I totally thought it was is why. Phx 1.4->1.5 breaks `Phoenix Instrumentation` in favor of Telemetry. I didn't realize spandex phoenix worked sans `Phoenix Instrumentation` config.

**Comment by novaugust** [comment]
Oh, regarding the original logs issue though: switching to telemetry means your trace doesn't start until you `plug Plug.Telemetry, prefix: ...`. so if you're plugging your logging plug before you plug telemetry, your logging won't include telemetry data.

**Comment by zachdaniel** [comment]
It seems there is a reasonable/expected workaround here, specifically that you can just move your logger plug to after your telemetry plug.

**Comment by michaelst** [comment]
I think this may need to be revisited now with the latest phoenix, I don't think there is a way to move telemetry above the Logger plug anymore
