### ISSUE TITLE
SpandexDatadog.ApiServer `noproc` can cause telemetry to detach

### ISSUE THREAD

**Issue by novaugust** [spandex-project/spandex_phoenix#39]
Telemetry handlers can't ever cause exceptions; if they do, they're detached.

SpandexDatadog.ApiServer can raise a `noproc` genserver exception when sending traces:

```
Handler "spandex-endpoint-telemetry" has failed and has been detached. Class=:exit
Reason={:noproc, {GenServer, :call, [SpandexDatadog.ApiServer, {:send_trace, ........}
```

fix: wrap the handle functions in catches for this exception and change it to a noop

**addendum**: sorry for the terse issue, writing this down late at night last thing before bed ^.^

**Comment by GregMefford** [comment]
Thanks for pointing out the issue!
Can you check in your supervision tree and see if `SpandexDatadog.ApiServer` is started before your `Endpoint` (assuming you're using Phoenix)? If you're trying to send traces before the ApiServer is started, then that either means that it crashed or things were started out of order, I think.

**Comment by zachdaniel** [comment]
I think regardless we might want to rescue exceptions there so as to avoid detaching the handler?

**Comment by GregMefford** [comment]
Yeah I'm conflicted because that's sort of counter to the Telemetry philosophy of either getting it right or getting out of the way. If you have your supervision tree in the right order and you have `:rest_for_one` strategy, the it takes care of itself for the most part without lots of `try/rescue`

**Comment by novaugust** [comment]
sorry for not following up gang! missed the notifications and work's going crazy as election season ramps up.

> Can you check in your supervision tree and see if SpandexDatadog.ApiServer is started before your Endpoint
Can confirm spandex is up before server. This error has happened hours into the server running, as opposed to during startup

**Comment by novaugust** [comment]
I'll try to do some more digging into this next week - i finally get to pick up my apm work. 

I just searched for a recurrence of this log and nothing came up (I think we retain for 1 week?), so at this point it could be that I was running on an older version of something and we went kaboom. If I don't find anything next week i'll just close the issue and we'll pretend this never happened

**Comment by GregMefford** [comment]
I'll go ahead and close this because I'm trying to clean up lingering issues if I can, but don't hesitate to let us know if you see it happening again. A `noproc` error definitely indicates that the process wasn't alive when you tried to call it, which isn't good but is clearly a thing that could happen transiently if something crashes and restarts.
