### ISSUE TITLE
Feature Wishlists

### ISSUE THREAD

**Issue by novaugust** [spandex-project/spandex_phoenix#8]
Hey team! Thanks to Greg, this + ecto went into production over the last two days. Have already come up with a few questions

1. how do i keep 404s from showing up as errors (when a php script kiddy rolls by checking for vulnerabilities it creates a bunch of nonsense error spans)
2. can i stop tracing OPTIONS calls? that essentially doubles my tracing count and thus my datadog bill
3. I have an endpoint like "phone/:phone_number_e164/lookup", which should be used like "phone/1112225555/lookup". you've helped me notice that we have clients pinging it with whitespace before the phone number, resulting in "phone/ 1112225555/lookup". our phone parsing library deals with it without a problem, stripping the whitespace for us. BUT, spandex is failing to recognize that this is a single endpoint, and so is reporting each trace as their own individual trace
<img width="794" alt="screen shot 2018-11-29 at 9 49 12 am" src="https://user-images.githubusercontent.com/1207005/49241261-2716b180-f3bc-11e8-8e1e-de20babfeb1b.png">
router definition is

```ex
scope "/internal", ... do
    get "/phone_numbers/:phone_number/lookup", LookupController, :show
  end
```

**Comment by GregMefford** [comment]
Thanks! ❤️

1. I actually thought we didn’t do that anymore in `spandex_phoenix`. Will have to look into it some more.

2. Check out the `customize_metadata` option, which allows you to add/remove/modify any of the defaults that you want to: https://hexdocs.pm/spandex_phoenix/SpandexPhoenix.html#content

3. Oh nice! That looks like a bug, but I’d need to dig into it a bit and see whether it’s fix-able or not. My guess is that you’re updating the params in a plug so that they no longer exactly match what’s in the original URL, which is how we infer what the route was. Unfortunately, Phoenix doesn’t store what the route name was; they only compile a function that matches, not store the route name in the Conn like Plug does 😞.

**Comment by GregMefford** [comment]
I hate how we parse out the route too, but when I dug into it, it looked like Plug.Router does save the name of the route, but Phoenix.Router does not, just because of the way they do it. It would probably be possible to write a PR to Phoenix that would add that feature, but obviously that’s a long lead-time to get it into your app. 😅

**Comment by zachdaniel** [comment]
I don't have time to look at it right now, but I tried a quick check and I can't recreate the problem with the path params in one of my spandex implementations. Adding a space in the route doesn't cause that for me. Are you in some way altering the `path_info` or `path_params` on the way in?

**Comment by novaugust** [comment]
re: 404s, these would be the result of phoenix raising `%NoRouteError{}`s - like i said, drive by php vulnerability checking. the normal `put_status(404)` is fine

**Comment by novaugust** [comment]
re: :phone_number, i'm not doing anything weird to the conn anywhere in there. params is never even touched

**Comment by novaugust** [comment]
Okay, did some digging into our client who's calling us. Turns out, they're properly doing e164 phone numbers per our spec, it's just getting misreported somewhere along the way when you do your url -> resource conversation. they are hitting our endpoint like

```
/phone_number/+15551234567/lookup
```
and so I'm guessing that `+` is screwing things up somehow eh

**Comment by novaugust** [comment]
here's your culprit

```
iex(6)> URI.decode_www_form("+15551234567")
" 15551234567"
```

**Comment by zachdaniel** [comment]
Shouldn't they be sending it URI encoded on the way in? It should be sent as `%2B`, right?

**Comment by zachdaniel** [comment]
Ah, maybe we should just be using `URI.decode/1`?

**Comment by novaugust** [comment]
Now the only issue left is that I have 15 pages of 1 requests to `GET /some/vulnerability.php :: Requests 1 | Errors 1`
any advice on gathering traces that are reporting `Phoenix.NoRouteError`s? if I can do that, I can change all their metadata to report something like `GET NoRouteError` and call it good.

**Comment by zachdaniel** [comment]
Hmm...that’s a tough one. I’ll have to think about it. You’d have to update the resource for all
Of the spans, and there is an `update_all_spans` function, but I generally wouldn’t recommend using that. Your better bet may be to add a catch all route at the bottom that goes to a NotFoundController and then render a 404 there.

**Comment by novaugust** [comment]
re 404s, here's an experiment i'm trying out: https://github.com/novaugust/spandex_phoenix/pull/1/files

**Comment by zachdaniel** [comment]
@novaugust 	I think we should pretty much just go for your solution. We'll need a major version bump unless we make it configurable, and make the old behavior the default. I think that would be fine too, to just put `not_found_resource: "Not Found"`, and if they don't configure a resource to use, we can use the current behavior of deriving it from the route. What do you think?

**Comment by novaugust** [comment]
I'm down, but rather than making the configuration api even larger, maybe leave it out til someone asks for it? 
and yeah, my name for it is dumb in that work, just `Not Found` is much better ;)

**Comment by zachdaniel** [comment]
It’s been cited to me as an annoyance from others as well, so I think it would be a good change. I think you’re right about the config. Let’s just make the change and put it in a major version release. There would be workarounds for those who don’t like the behavior.

**Comment by novaugust** [comment]
I think if we get a new release this issue can be closed eh :) thanks for all the help you two

**Comment by zachdaniel** [comment]
@GregMefford 	I won't be at a computer for a while, so if you want to do the release feel free.

**Comment by novaugust** [comment]
just saw the release, thanks @zachdaniel
